version: '3.7'

services:
  jira:
    container_name: jira-software
    restart: always
    image: cptactionhank/atlassian-jira-software
    volumes:
      - jira_data:/var/atlassian/jira
    ports:
      - 8080:8080
  confluence:
    container_name: confluence
    restart: always
    image: atlassian/confluence-server
    volumes:
      - confluence_data:/var/atlassian/application-data/confluence
    ports :
      - "8090:8090"
      - "8091:8091"
volumes:
  jira_data:
  confluence_data: